name: "Pull Request Labeler"

on:
  pull_request_target:  # Usamos pull_request_target por seguridad y acceso a secrets
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write  # Necesario para poder añadir etiquetas

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true  # Opcional: elimina etiquetas que ya no aplican